
# H2
spring:
  datasource:
    url: jdbc:h2:mem:cryptodb;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:file:/tmp/cryptodb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
    #data: file:/<path>/data.sql
#   pool size    
#    hikari:
#      maximum-pool-size: 50
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      max_fetch_depth: 3
      hbm2ddl:
        auto: update
      ddl-auto: update  
      show_sql: true
  h2:
    console:
      enabled: true
      path: /admin/h2-console
  main:
    allow-bean-definition-overriding: true
  security: 
    user:
      name: admin
      password: admin
      roles: ADMIN

    