spec:
  template:
    metadata:
      labels:
         ambiente: test
    spec:
      volumes:
      - name: crypto-config
        configMap:
          name: crypto-config-test
      containers:
      - env:
        - name: SPRING_CONFIG_VOLUME
          value: /etc/crypto/config
        - name: H2_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: crypto-secrets-test
        - name: H2_PWD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: crypto-secrets-test
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: crypto-secrets-test
        - name: ADMIN_PWD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: crypto-secrets-test
        volumeMounts:
        - name: crypto-config
          readOnly: true
          mountPath: /etc/crypto/config
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
