apiVersion: v1
kind: Service
metadata:
  name: crypto-pre
  namespace: parer
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: old-cryptolibrary-web
    ambiente: pre
