
# MYSQL
spring:
  datasource:
    url: jdbc:mysql://mysql-verificafirma-crypto:3306/cryptodb
    driver-class-name: com.mysql.jdbc.Driver
    username: cryptodb
    password: MKImX8LTdFf5vT3I
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    hikari:
      maximum-pool-size: 15
      pool-name: ParerCryptoHikariPool
      maxLifeTime : 600000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      max_fetch_depth: 3
      ddl-auto: update
      show_sql: false
  main:
    allow-bean-definition-overriding: true
  security: 
    user:
      name: admin
      password: admin
      roles: ADMIN
   