# H2
spring:
  datasource:
    url: jdbc:oracle:thin:@parer-vora-b03.ente.regione.emr.it:1521/PARER19S.ente.regione.emr.it
    driver-class-name: oracle.jdbc.OracleDriver
    username: SACER_CRYPTO
    password: CyDBDBaOh4Oac_Kmr5NZ
    hikari:
      maximum-pool-size: 15
      pool-name: ParerCryptoHikariPool
      maxLifeTime : 600000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      max_fetch_depth: 3
      ddl-auto: update
      show_sql: false
  main:
    allow-bean-definition-overriding: true
  security: 
    user:
      name: admin
      password: admin
      roles: ADMIN
   