apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: verificafirma-crypto
  template: verificafirma-crypto-springboot
metadata:
  annotations:
    description: |-
      Template microservizio verifica firma CRYPTO JDK17 OracleDB (vedere https://gitlab.ente.regione.emr.it/parer/okd/crypto.git)
    iconClass: icon-spring
    openshift.io/display-name: Microservice CRYPTO
    openshift.io/documentation-url: https://gitlab.ente.regione.emr.it/parer/okd/crypto
    openshift.io/long-description: Il template fornisce la creazione del microservizio CRYPTO con selettore sul tipo di ambiente (svil/test/pre/etc.)
    openshift.io/provider-display-name: Parer (Regione Emilia Romagna)
    openshift.io/support-url: https://gitlab.ente.regione.emr.it/parer
    tags: springboot,crypto
    template.openshift.io/bindable: "false"
  name: verificafirma-crypto-springboot
objects:
- apiVersion: v1
  stringData:
    admin-password: ${ADMIN_PASSWORD}
    admin-user: ${ADMIN_USER}
    database-url: ${DB_URL}
    database-password: ${DB_PASSWORD}
    database-user: ${DB_USER}
  kind: Secret
  metadata:
    name: crypto-secrets
  type: Opaque
- apiVersion: v1
  data:
    .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5lbnRlLnJlZ2lvbmUuZW1yLml0L3BhcmVyLyI6eyJ1c2VybmFtZSI6Im9rZF9kZXBsb3kiLCJwYXNzd29yZCI6IlhUWkJ5V1lBQnZ4UVVMOFdreHFxIiwiZW1haWwiOiJnaXRsYWJAZGVwbG95LmxvY2FsIn19fQ==
  kind: Secret
  metadata:
    name: gitlab-registry-token
  type: kubernetes.io/dockerconfigjson
- apiVersion: v1
  data:
    application-${PROFILE}.yaml: |
      server:
        port: 8080
        tomcat:
          accesslog:
            enabled: false      
            directory: /dev
            prefix: stdout
            buffered: false
      spring:
        #profiles:
          #active: prod
        security: 
          user:
            name: ${ADMIN_USER}
            password: ${ADMIN_PWD}
            roles: ADMIN  
        datasource:
            url: ${DB_URL}
            driver-class-name: oracle.jdbc.OracleDriver
            username: ${DB_USER}
            password: ${DB_PASSWORD}
            hikari:
              auto-commit: false
              minimum-idle: 5
              maximum-pool-size: 15
              pool-name: ParerCryptoHikariPool
              idle-timeout: 360000
              max-lifetime: 360000
        jpa:
          open-in-view: false
          database-platform: org.hibernate.dialect.Oracle12cDialect
          hibernate:
            max_fetch_depth: 3
            ddl-auto: update
            show_sql: false
            hbm2ddl:
              auto: update
        main:
          allow-bean-definition-overriding: true
      # gestione actuators
      management:
        endpoint: 
          health:
          show-details: when_authorized    
        endpoints:
        web: 
          exposure: 
            include: health
      # LOGGING (vedi lobgback.xml)
      # CRON  
      cron:
        thread:
          pool:
            size: 2
        ca:
        enable: true
        # ogni giorno alle 3:00
        sched: "* 0 3 * * *"
        #initial-delay: 180000       
        #delay: 7200000
        crl:
        enable: true
          # ogni giorno alle 1:00
        sched: "* 0 1 * * *"
        #initial-delay: 240000
        #delay: 3600000
      # CRYPTO METTERE LE INFO DI PRODUZIONE!!!
      parer:
        crypto:
          TSAServiceURL: https://timestamp.firmacerta.it
          TSAAuthScope: timestamp.firmacerta.it
          TSAUser: bc8d6aba
          TSAPass: 2ecb7910
          trovaCAOnline: false
      logging:
        config: file:./config/logback.xml
      servlet:
        multipart:
          max-file-size: 2GB
          max-request-size: 2GB                                  
    logback.xml: |-
      <configuration>
          <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
              <layout class="ch.qos.logback.classic.PatternLayout">
                  <Pattern>
                      %d %-5p [%c] \(%t\) [%X{uuid}] %m %replace(%ex){'[\r\n]+', '\\n'}%nopex%n
                  </Pattern>
              </layout>
          </appender>
          
          <logger name="it.eng.parer.crypto" level="info" additivity="false">
              <appender-ref ref="CONSOLE"/> 
          </logger> 
          <logger name="org.springframework" level="info" additivity="false">
              <appender-ref ref="CONSOLE"/> 
          </logger> 
        <logger name="org.apache" level="info" additivity="false">
              <appender-ref ref="CONSOLE"/> 
        </logger>
        <logger name="org.hibernate" level="info" additivity="false">
              <appender-ref ref="CONSOLE"/> 
          </logger>
                    
          <root level="info">
              <appender-ref ref="CONSOLE"/>
          </root>
      </configuration> 
  kind: ConfigMap
  metadata:
    name: verificafirma-crypto-config
- apiVersion: v1
  kind: Service
  metadata:
    name: verificafirma-crypto
    labels:
      app: verificafirma-crypto
      expose: "true"
  name: verificafirma-crypto
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: verificafirma-crypto
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 10m
    name: verificafirma-crypto
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: verificafirma-crypto
      weight: 100
    wildcardPolicy: None
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: verificafirma-crypto
      group: it.eng.parer
      gl_log_application: crypto
      gl_tags: ${AMBIENTE}
    name: verificafirma-crypto
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: verificafirma-crypto
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
      resources:
        limits:
          cpu: 100m
          memory: 100Mi          
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: RollingUpdate    
    template:
      metadata:
        labels:
          app: verificafirma-crypto
          gl_log_application: crypto
          gl_tags: ${AMBIENTE}
          group: it.eng.parer
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: TZ
            value: Europe/Rome
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: verificafirma-eidas-secrets
                key: database-url                 
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: crypto-secrets
                key: database-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: crypto-secrets
                key: database-password
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: crypto-secrets
                key: admin-user
          - name: ADMIN_PWD
            valueFrom:
              secretKeyRef:
                name: crypto-secrets
                key: admin-password
          - name: LANG
            value: en_US.UTF-8
          - name: AB_JOLOKIA_OFF
            value: 'true'
          - name: JAVA_OPTS_APPEND
            value: >-
              -Dspring.profiles.active=${PROFILE} -XX:+UnlockExperimentalVMOptions 
              -XX:+UseContainerSupport -Dsun.zip.disableMemoryMapping=true
              -Dcom.sun.management.jmxremote=true
              -Dcom.sun.management.jmxremote.port=3000
              -Dcom.sun.management.jmxremote.rmi.port=3001
              -Djava.rmi.server.hostname=127.0.0.1
              -Dcom.sun.management.jmxremote.authenticate=false
              -Dcom.sun.management.jmxremote.ssl=false
          - name: JAVA_MAX_MEM_RATIO
            value: '90'
          - name: JAVA_INITIAL_MEM_RATIO
            value: '40'
          image: ${REGISTRY}:${IMGTAG}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 180
          resources:
            limits:
              cpu: 800m
              memory: 3Gi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/crypto/config
            name: verificafirma-crypto-config
            readOnly: true
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: gitlab-registry-token
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 50
        securityContext:
          runAsUser: 1000660000
          fsGroup: 1000660000        
        volumes:
        - configMap:
            defaultMode: 420
            name: verificafirma-crypto-config
          name: verificafirma-crypto-config
    test: false
    triggers:
    - type: ConfigChange
parameters:
- description: Registry immagine da utilizzare
  displayName: registry
  name: REGISTRY
  required: false
  value: registry.ente.regione.emr.it/parer/okd/crypto
- description: Nome dal tag dell'immagine da utilizzare (default latest)
  displayName: imagetag
  name: IMGTAG
  required: false
  value: latest
- description: Nome dell'ambiente (e.g. svil/pre/test)
  displayName: ambiente
  name: AMBIENTE
  required: true
- description: Nome utente per accesso interfaccia web.
  displayName: Nome utente per accesso interfaccia web
  name: ADMIN_USER
  value: admin
- description: Password per accesso interfaccia web.
  displayName: Password per accesso interfaccia web
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: ADMIN_PASSWORD
- description: URL database.
  displayName: URL database
  required: true
  name: DB_URL
- description: Nome utente per accesso db.
  displayName: Nome utente per accesso db
  name: DB_USER
  value: cryptodb
- description: Password per accesso db.
  displayName: Password per accesso db
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: DB_PASSWORD
- description: Nome profilo springboot
  displayName: Nome profilo springboot
  name: PROFILE
  required: true